Adapt 4.9 patch to manual KSU hooks
Since importing KSU hooks is better than using kprobes adapt the patch to them, like 4.14 and 4.19 already did. Doing otherwise leads to this error while compiling

../fs/open.c:398:19: error: mixing declarations and code is a C99 extension [-Wdeclaration-after-statement]
  398 |         struct filename* fname;